from encoder import *

def Srg(MPSeqData):
    if MPSeqData==encode_IRtoMPS(0x70): return 0
    if MPSeqData==encode_IRtoMPS(0x71): return 1
    if MPSeqData==encode_IRtoMPS(0x72): return 2
    if MPSeqData==encode_IRtoMPS(0x73): return 3
    if MPSeqData==encode_IRtoMPS(0x74): return 4
    if MPSeqData==encode_IRtoMPS(0x75): return 5
    if MPSeqData==encode_IRtoMPS(0x76): return 6
    if MPSeqData==encode_IRtoMPS(0x77): return 7
    if MPSeqData==encode_IRtoMPS(0x78): return 8
    if MPSeqData==encode_IRtoMPS(0x79): return 9
    if MPSeqData==encode_IRtoMPS(0x7a): return 10
    if MPSeqData==encode_IRtoMPS(0x7b): return 11
    if MPSeqData==encode_IRtoMPS(0x7c): return 12
    if MPSeqData==encode_IRtoMPS(0x7d): return 13
    if MPSeqData==encode_IRtoMPS(0x7e): return 14
    if MPSeqData==encode_IRtoMPS(0x7f): return 15
    if MPSeqData==encode_IRtoMPS(0x80): return 0
    if MPSeqData==encode_IRtoMPS(0x81): return 1
    if MPSeqData==encode_IRtoMPS(0x82): return 2
    if MPSeqData==encode_IRtoMPS(0x83): return 3
    if MPSeqData==encode_IRtoMPS(0x84): return 4
    if MPSeqData==encode_IRtoMPS(0x85): return 5
    if MPSeqData==encode_IRtoMPS(0x86): return 6
    if MPSeqData==encode_IRtoMPS(0x87): return 7
    if MPSeqData==encode_IRtoMPS(0x88): return 8
    if MPSeqData==encode_IRtoMPS(0x89): return 9
    if MPSeqData==encode_IRtoMPS(0x8a): return 10
    if MPSeqData==encode_IRtoMPS(0x8b): return 11
    if MPSeqData==encode_IRtoMPS(0x8c): return 12
    if MPSeqData==encode_IRtoMPS(0x8d): return 13
    if MPSeqData==encode_IRtoMPS(0x8e): return 14
    if MPSeqData==encode_IRtoMPS(0x8f): return 15
    if MPSeqData==encode_IRtoMPS(0x90)+1: return 0
    if MPSeqData==encode_IRtoMPS(0x91)+1: return 1
    if MPSeqData==encode_IRtoMPS(0x92)+1: return 2
    if MPSeqData==encode_IRtoMPS(0x93)+1: return 3
    if MPSeqData==encode_IRtoMPS(0x94)+1: return 4
    if MPSeqData==encode_IRtoMPS(0x95)+1: return 5
    if MPSeqData==encode_IRtoMPS(0x96)+1: return 6
    if MPSeqData==encode_IRtoMPS(0x97)+1: return 7
    if MPSeqData==encode_IRtoMPS(0x98)+1: return 8
    if MPSeqData==encode_IRtoMPS(0x99)+1: return 9
    if MPSeqData==encode_IRtoMPS(0x9a)+1: return 10
    if MPSeqData==encode_IRtoMPS(0x9b)+1: return 11
    if MPSeqData==encode_IRtoMPS(0x9c)+1: return 12
    if MPSeqData==encode_IRtoMPS(0x9d)+1: return 13
    if MPSeqData==encode_IRtoMPS(0x9e)+1: return 14
    if MPSeqData==encode_IRtoMPS(0x9f)+1: return 15